version: "3.8"
services:
  catalog-service:
    image: anveshlp/bookstore-catalog-service:latest
    container_name: catalog-service
    ports:
      - "8081:8081"
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
        - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped

  order-service:
    image: anveshlp/bookstore-order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORDERS_CATALOG_SERVICE_URL=http://catalog-service:8081
      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - ORDERS_CATALOG_REDIS_SERVICE_URL=redis://redis:6379
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_HOST=kafka:9092
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1200m

  notification-service:
    image: anveshlp/bookstore-notification-service:latest
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_HOST=kafka:9092
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      notifications-db:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 1200m

