version: "3.8"
services:
  catalog-service:
    image: anveshlp/bookstore-catalog-service:latest
    container_name: catalog-service
    ports:
      - "8081:8081"
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
        - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
