name : catalog service
on:
  push:
    paths:
      - catalog-service/** # Trigger on changes to the catalog-service directory
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'


      - name: Build with Maven
        run: ./mvnw -ntp verify
